---
- name: Bootstrap Debian for LFS Development
  hosts: all
  become: yes
  vars:
    dotfiles_repo: "https://github.com/laugenbrezel1004/dotfiles.git"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages for LFS and development
      apt:
        name:
          - build-essential
          - binutils
          - bison
          - gawk
          - gcc
          - g++
          - make
          - patch
          - texinfo
          - flex
          - automake
          - autoconf
          - libtool
          - glibc-dev
          - linux-headers-generic
          - git
          - curl
          - wget
          - vim
          - neovim
        state: present

    - name: Create lfs user
      user:
        name: lfs
        shell: /bin/bash
        home: /home/lfs
        create_home: yes

    - name: Ensure /mnt directory exists
      file:
        path: /mnt
        state: directory
        mode: '0755'

    - name: Install yadm for dotfiles management
      apt:
        name: yadm
        state: present

    - name: Clone dotfiles for lfs user
      become_user: lfs
      command: yadm clone {{ dotfiles_repo }}
      args:
        creates: /home/lfs/.yadm/repo.git
      register: yadm_clone
      failed_when: yadm_clone.rc != 0 and yadm_clone.rc != 1

    - name: Run yadm bootstrap if dotfiles include a bootstrap script
      become_user: lfs
      command: yadm bootstrap
      args:
        chdir: /home/lfs
      when: yadm_clone.rc == 0
      ignore_errors: yes

    - name: Ensure lfs user has proper permissions for home directory
      file:
        path: /home/lfs
        owner: lfs
        group: lfs
        mode: '0755'
        recurse: yes
